# Generated by Django 4.2.1 on 2023-11-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="images",
        ),
    ]
